# Generated by Django 3.2.22 on 2024-04-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_auto_20240422_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网格区域名')),
                ('desc', models.CharField(max_length=32, verbose_name='网格简称')),
            ],
            options={
                'verbose_name_plural': '区域表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('avatar', models.FileField(max_length=128, upload_to='avatar', verbose_name='头像')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='采集人员姓名')),
                ('name_pinyin', models.CharField(max_length=32, null=True, verbose_name='姓名拼音')),
                ('avatar', models.ImageField(default='default.png', upload_to='collection/%Y/%m/%d/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.area', verbose_name='网格区域')),
            ],
            options={
                'verbose_name_plural': '采集表',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.userinfo', verbose_name='负责用户'),
        ),
    ]
