# Generated by Django 3.2.22 on 2024-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_auto_20240422_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='face_token',
            field=models.CharField(max_length=64, null=True, verbose_name='百度Token'),
        ),
    ]
